### ISSUE TITLE
Restrict collections to collect info for

### ISSUE THREAD

**Issue by freeseacher** [y8/mongo_collection_exporter#1]
Please make namespaces defined in config works as expected 
```# Namespaces to export.
#
# For example, to export metrics only from one collection `foo` from database
# `bar` specify `bar.foo`. To export all collections from `bar` just specify
# `bar.*`.
#
# If no namespace given, all discovered namespaces will be exported.
# namespaces:
#  - foo.*
```

Its better to be done in such way 
```
namespaces:
  - include:
    - *
  - exclude:
    - foo.*
    - *.bar
```

where exclude wins include.

Tnx.
